'\" t
'\" <<ital-is-var>>
'\" <<bold-is-fixed>>
.TH MAPPER 6 "GMA-Mapper 4.9.3" 31-May-2023 "Games" \" @@mp@@
.SH NAME
mapper \- GMA battle grid map
.SH SYNOPSIS
'\" <<usage>>
.LP
.na
.B gma
.B mapper
.B \-\-
.B \-\-help
.LP
.B gma
.B mapper
.RB [ \-display
.IR name ]
.RB [ \-geometry
.IR value ]
.RI [ "other wish options" ]
.B \-\-
.RB [ \-A ]
.RB [ \-a ]
.RB [ \-B ]
.RB [ \-b
.IR pct ]
.RB [ \-C
.IR file ]
.RB [ \-c
.RI [ image\fB=\fP ] name [\fB:\fP color ]]
.RB [ \-D ]
.RB [ \-d ]
.RB [ \-f
.IR fmt ]
.RB [ \-G
.IR n [\fB+\fP x [\fB:\fP y ]]]
.RB [ \-g
.IR n [\fB+\fP x [\fB:\fP y ]]]
.RB [ \-h
.IR hostname ]
.RB [ \-k ]
.RB [ \-l ]
.RB [ \-M
.IR module ]
.RB [ \-n ]
.RB [ \-P
.IR pass ]
.RB [ \-p
.IR port ]
.RB [ \-S
.IR profile ]
.RB [ \-t
.IR transcript ]
.RB [ \-u
.IR name ]
.RB [ \-X
.IR proxyhost ]
.RB [ \-x
.IR proxyurl ]
.RB [ \-\-button\-size
.BR small | medium | large ]
.RB [ \-\-chat\-history
.IR n ]
.RB [ \-\-curl\-path
.IR path ]
.RB [ \-\-curl\-url\-base
.IR url ]
.RB [ \-\-dark ]
.RB [ \-\-debug\-protocol ]
.RB [ \-\-mkdir\-path
.IR path ]
.RB [ \-\-nc\-path
.IR path ]
.RB [ \-\-no\-animate ]
.RB [ \-\-no\-blur\-all ]
.RB [ \-\-preferences
.IR path ]
.RB [ \-\-scp\-dest
.IR dir ]
.RB [ \-\-scp\-path
.IR path ]
.RB [ \-\-scp\-server
.IR hostname ]
.RB [ \-\-ssh\-path
.IR path ]
.RB [ \-\-update\-url
.IR url ]
.LP
.B gma
.B mapper
.RB [ \-display
.IR name ]
.RB [ \-geometry
.IR value ]
.RI [ "other wish options" ]
.B \-\-
.RB [ \-\- [ no\- ] animate ]
.RB [ \-\- [ no\- ] blur\-all ]
.RB [ \-\-blur\-hp
.IR pct ]
.RB [ \-\-button\-size
.BR small | medium | large ]
.RB [ \-\-config
.IR file ]
.RB [ \-\-character
.RI [ image\fB=\fP ] name [\fB:\fP color ]]
.RB [ \-\-chat\-history
.IR n ]
.RB [ \-\-curl\-path
.IR path ]
.RB [ \-\-curl\-url\-base
.IR url ]
.RB [ \-\-dark ]
.RB [ \-\-debug ]
.RB [ \-\-debug\-protocol ]
.RB [ \-\-guide
.IR n [\fB+\fP x [\fB:\fP y ]]]
.RB [ \-\-host
.IR hostname ]
.RB [ \-\-image\-format
.IR fmt ]
.RB [ \-\-keep\-tools ]
.RB [ \-\-major
.IR n [\fB+\fP x [\fB:\fP y ]]]
.RB [ \-\-mkdir\-path
.IR path ]
.RB [ \-\-module
.IR module ]
.RB [ \-\-nc\-path
.IR path ]
.RB [ \-\-no\-chat ]
.RB [ \-\-password
.IR pass ]
.RB [ \-\-port
.IR port ]
.RB [ \-\-preferences
.IR path ]
.RB [ \-\-preload ]
.RB [ \-\-proxy\-host
.IR proxyhost ]
.RB [ \-\-proxy\-url
.IR proxyurl ]
.RB [ \-\-scp\-dest
.IR path ]
.RB [ \-\-scp\-path
.IR path ]
.RB [ \-\-scp\-server
.IR hostname ]
.RB [ \-\-select
.IR profile ]
.RB [ \-\-ssh\-path
.IR path ]
.RB [ \-\-transcript
.IR filename ]
.RB [ \-\-update\-url
.IR url ]
.RB [ \-\-username
.IR name ]
.ad
'\" <</usage>>
.LP
Options cannot be combined into a single CLI argument.
They are evaluated in the order they are received.
.LP
As shown above, if you have the GMA Core package installed, you may invoke the
.B mapper
program via the main
.B gma
program as
.RS
.LP
'\" <<TeX>>
'\" \begin{Coding!}
'\" `$ gma mapper` \dots
'\" \end{Coding!}
.B gma
.B mapper
\&...
'\" <</TeX>>
.RE
.LP
If you installed 
.B mapper
as a stand-alone package by itself, you need to invoke it by running the
.B mapper.tcl
program found in the
.B bin
directory of the
.B GMA-Mapper
package as unpacked or cloned from git.
Depending on your system's particular configuration, you may be able to run it
directly, as
.RS
.LP
'\" <<TeX>>
'\" \begin{Coding!}
'\" `$ bin/mapper.tcl`
'\" \end{Coding!}
.B bin/mapper.tcl
'\" <</TeX>>
.RE
or you may need to explicitly run the
.BR wish (1)
interpreter in a form such as
.RS
.LP
'\" <<TeX>>
'\" \begin{Coding!}
'\" `$ wish bin/mapper.tcl`\\
'\" `$ wish8.6 bin/mapper.tcl`
'\" \end{Coding!}
.B wish 
.B bin/mapper.tcl
.br
.B wish8.6
.B bin/mapper.tcl
'\" <</TeX>>
.RE
.SH DESCRIPTION
.LP
The
.B mapper
program displays a battle grid map for the players to see their tactical positions
with respect to their opponents and features of their environment (e.g., dungeon
rooms).
.LP
If one or more map file names are listed on the command line, those files are loaded
into the grid display.  Otherwise, a blank map grid is shown.  Map files may subsequently
be loaded via interactive commands or upon request from a control service (see the
.B \-h
option.
.LP
See notes at the bottom of this manpage for installation requirements.
.SH CONFIGURATION
.LP
Starting with version 4.4, the mapper now uses an integrated preferences editor for
its configuration. This eliminates the necessity of controlling the mapper via command-line
options and/or configuration files, although those may still also be used.
.LP
Selecting
'\" <<TeX>>
'\" \menu{Edit > Preferences\dots}
.B Edit 
.B > 
.B Preferences...
'\" <</TeX>>
from the menu calls up the preference editor window. There you can enter global
preference settings as well as server-specific ones. In the latter case, multiple
server profiles may be created. Selecting one of these profiles in the list will make it
the current profile. Every time the mapper is started, that server profile will be loaded
and a connection opened to the server named in it.
.LP
If you wish to simply select a different server profile as the current one and connect to it,
access the
'\" <<TeX>>
'\" \menu{Play > Connect to}
.B Play
.B >
.B "Connect to"
'\" <</TeX>>
menu and choose the desired server profile.
.LP
Some preferences may not take effect until the mapper is restarted. When leaving the
editor window, you will be given the opportunity to restart the mapper if you desire.
.LP
Once the editor window is used, a preferences data file will be created as
.BR "~/.gma/mapper/preferences.json" .
If that file exists, it will always be loaded when the mapper starts. In this case,
the mapper will not load the
.B "~/.gma/mapper/mapper.conf"
file anymore unless explicitly requested via command-line option.
.LP
If any command-line options are given, they will override the settings loaded at program start-up
from the
.B preferences.json
file.
.SH "HELPER PROGRAMS"
.LP
The
.B mapper
client makes use of a few other programs to facilitate the efficient handling
of data transfers. These are only used if the client is working in networked mode rather
than as a stand-alone map drawing program.
'\" <<desc>>
.TP
.B curl
Assuming the GM (or whomever is administrating the map assets) has arranged for a web server
to host content for the map, the
.B mapper
client will invoke the
.BR curl (1)
program to actually retrieve the files from that server. If needed, you will need to provide
options and/or configuration file parameters as documented below to let
.B mapper
know where to find the 
.B curl
binary and what options it needs to find the web server, navigate through proxy servers, etc.
.TP
.B scp
For users with privileges to
'\" <</ital-is-var>>
.I store
'\" <<ital-is-var>>
data on the web server (generally, this would be the GM or other designated administrative users,
not the general player group), 
.B mapper
will invoke
.BR scp (1)
to copy new data files up to the server. For example, in store-and-forward mode, when opening
a local data file or pushing map contents out to other clients, 
.B mapper
checks to see if the server has the data file(s) available for everyone to download. If not,
it will use
.B scp
to upload them to the server before sending out a command to peer clients to retrieve them.
.RS
.LP
This requires that the user is authorized to perform this action on the remote server.
Usually this is done by having an SSH certificate loaded via
.BR ssh-agent (1)
and the server set up to recognize that for the needed operations without requiring a
password to be manually entered.
.RE
.TP
.B ssh
Along with the use of
.B scp
to transfer new data to the web server, 
.B mapper
will use
.BR ssh (1)
to create directories and set file permissions as needed on the server for the content being
uploaded. 
'\" <</>>
.SH OPTIONS
.LP
The following options control the behavior of
.BR mapper .
'\" <<list>>
.TP 20
.BR \-a ", " \-\-animate
This option causes
the mapper to make a lame attempt to \*(lqanimate\*(rq the appearance
of objects being drawn onto the screen by updating the display after each one.
(The author was feeling oddly nostalgic about working with the Tektronix storage-screen
computer displays of his childhood at the time. If you don't know what that means, go
watch an episode of the 1970s-era Battlestar Galactica and look at most of their
computer screens.)
.TP
.BR \-A ", " \-\-no\-animate
Suppress the animation effects enabled by the 
.B \-a
.RB ( \-\-animate )
option. This is the default, so it only needs to be given to cancel an
.B \-a
option which appeared previously or which was read from a configuration file.
.TP
.BR \-B ", " \-\-blur\-all
Normally, the imprecision introduced to health bar displays by the 
.B \-b
.RB ( \-\-blur\-hp )
option applies only to \*(lqmonsters\*(rq (opponents). With this option, it
applies to all participants.
.TP
.B \-\-no\-blur\-all
Cancels the effect of the
.B \-B
.RB ( \-\-blur\-all )
option.
.TP
.BI "\-b\fR, \fP\-\-blur\-hp " pct
This option \*(lqblurs\*(rq the health bar displays by rounding off the displayed
hit point total to only be accurate in
.IR pct -percent
intervals. For example, a setting of
.B 10
means the health bar will blur the value by 10%; in other words, rather than
every hit point showing proportionally on the health bar, the health bar will only
show 10 possible intermediate values, corresponding to the hit points being 1\-9%,
10\-19%, 20\-29%, ..., 90\-99% of the total, as well as 0% and 100%.
Thus, higher 
.I pct
values indicate less accurate displays. 
.RS
.LP
Setting 
.I pct
to 0 (or less) indicates that no blurring is desired; in this case the display is
precisely accurate. This is the default, but note that the hit points reported may
be blurred on the server (GM)'s side independently.
.LP
Once a creature reaches 0 hit points, no further blurring is
done, so the bleed-out sequence is accurate (but this is fairly quick for almost all
creatures and is of less consequence than the hit point totals while they are still
alive and fighting, so this was considered a better course of action).
.RE
.TP
.BI "\-\-button\-size " size
Change the size of the toolbar buttons. The
.I size
value may be any string starting with
.BR s ,
.BR m ,
or
.BR l ,
representing small, medium, or large-size icons. Small buttons are the default.
.TP
.BI "\-C\fR, \fP\-\-config " file
Read a set of command-line options from the named
.I file
as if they appeared at this point in the list of command-line
options. Only the long-form option names are allowed and are
given without the leading hyphens.
The file must contain a single option per line. Options which
take a parameter are separated from their parameter with an equals
sign (although this is currently not supported in the command line
itself). For example, a configuration file might contain the
following:
'\" <<TeX>>
'\"\begin{SourceCode}
'\"# My configuration settings
'\"scp-dest=/usr/local/game-support
'\"scp-server=www.example.org
'\"curl-url-base=https://www.example.org/game
'\"no-animate
'\"keep-tools
'\"\end{SourceCode}
.RS
.RS
.nf
.na
.B "# My configuration settings"
.B "scp-dest=/usr/local/game-support"
.B "scp-server=www.example.org"
.B "curl-url-base=https://www.example.org/game"
.B "no-animate"
.B "keep-tools"
.ad
.fi
.RE
'\" <</TeX>>
.LP
Note that any line whose very first character is an octothorpe
.RB (\*(lq # \*(rq)
is ignored as a comment.
.LP
If the file
.B ~/.gma/mapper/mapper.conf
exists, it is read first before command-line options or
(other) configuration files are loaded.
.LP
Note that more than one
.B \-\-config
(and/or
.BR \-C )
option may be given, in which case the files are read in the order they appear in the 
command line. This may be used to split up options into different files, such as general
settings common to all sessions, and specific settings based on networks or different games.
.RE
.TP
.BI "\-c\fR, \fP\-\-character \fR[\fP" image =\fR]\fP name \fR[\fP: color \fR]\fP
Add player
.I name
to the list of standard players tracked by the mapper.
This is the list that appears in the pop-up menu for placing
people onto the map.  If 
.I color
is also specified, that color is used for the threat zone
highlighting.  This may be a standard X11 color name, or
an RGB value in the form 
.BI # rgb,
.BI # rrggbb,
or
.BI # rrrgggbbb.
The default is \*(lqblue\*(rq.
.RS
.LP
If an image file will be used with the character that's not the same
name as the character, specify it as
.IB image = name
in this option.
.LP
Multiple
.B \-c
options may be given.  Each adds another name to the list.
.LP
Note that when the mapper is networked, the
default list of names actually comes from the server, so it
should not be necessary to specify these names to the client from
the command line or configuration file.
.RE
.TP
.BI "\-\-chat\-history " n
Limits the retained chat history to 
.I n
messages. When
.B mapper
starts, it reloads the chat history it had cached from the previous
session on the current
.I host
and 
.I port
but if that results in more than
.I n
messages being in the history, the list of messages is truncated to
the most recent
.I n
(both in-memory and in the cache file). Any additional messages
received will be kept, so the actual history will be a little
larger than
.I n
until the next time 
.B mapper
is started. If
.I n
is less than or equal to 0,
then no limit is placed on the history size.
The default limit is 512.
.TP
.BI "\-\-curl\-path " path
Specify the path to the
.BR curl (1)
program on your system, if the built-in default doesn't work for you.
This is used when fetching image and map files from the server.
.TP
.BI "\-\-curl\-url\-base " url
Specify the base URL on the data server. The files downloaded by mapper
clients will be in a directory hierarchy appended to this string.
.TP
.BR \-d ", " \-\-dark
This option changes the default color palette to use a darker background which
may be easier to look at for longer periods of time. On macOS systems running
up-to-date versions of Tcl/Tk (not the default legacy version supplied by
Apple), dark mode is automatically selected if the macOS session is also
configured for dark mode.
.TP
.BR \-D ", " \-\-debug
Increase debugging output level. Multiple 
.B \-D 
options further increase verbosity of debugging messages. These are displayed
in a separate window.
.TP
.BI \-\-debug\-protocol
Turns on debugging messages showing all interactions between client and server, and the client-side
procesesing that is done to support that interaction.
.TP
.BI "\-g\fR, \fP\-\-guide " n
Make every
.IR n th
gridline red (thick lines).
This is for minor guide lines. The value of
.I n
may be specified in all the same ways as for the
.BR \-G / \-\-major
option (see below).
.TP
.B \-\-help
Print a summary of the command invocation options and exit.
.TP
.BI "\-h\fR, \fP\-\-host " hostname
Connect to a map control service running on the designated host.  This will 
send updates to item positions, display of rooms, etc.
If this option is not specified, no control connection is made, and the mapper
runs in stand-alone mode.
.TP
.BR \-f ", " "\-\-image\-format gif" | png
Sets the preferred image file format to request when retrieving images from the server to display on the map.
.TP
.BR \-k ", " \-\-keep\-tools
Normally, map clients have their toolbars turned off to maximize
the available screen space for the battle map. The GM can turn on and off their toolbars from
his console as needed.  If this option is given, this causes the client to unconditionally
display its toolbar anyway. This is used for the main map run by the GM or whomever else is
managing the group map and needs the toolbar active, or if people just want to keep the toolbar all
the time.
.TP
.BI "\-G\fR, \fP\-\-major " n
Make every
.IR n th
gridline green (very thick lines).
This is for major guide lines on the map. 
.TP
.BI "\-G\fR, \fP\-\-major " n + o
As above, but offset the major guide lines to the right and down by
.I o
lines.
The
.B +
character is required, but the value of
.I o
may be negative, so the option 
.RB \*(lq \-G
.IB n +\-3\fR\*(rq\fP
would move the lines to the left and up by 3 lines.
.TP
.BI "\-G\fR, \fP\-\-major " n + x : y
If expressed this way, rather than use the same offset in both directions, move the guide
lines 
.I x
lines to the right and
.I y
lines down.
.TP
.BI "\-\-mkdir\-path " path
Specify the 
.I "server-side"
path to the
.BR mkdir (1)
program which will be used when uploading files
'\" <</ital-is-var>>
.I to
'\" <<ital-is-var>>
the data server (authorized users only).
.TP
.BI "\-M\fR, \fP\-\-module " module
Use the module ID code
.I module
for this session. This is used to differentiate server-side resources
between campaigns which have conflicting names. This is only needed 
for the mapper clients used as the forwarder in store-and-forward mode
(typically the GM's own client).
.TP
.BI "\-\-nc\-path " path
Specify the path to the
.BR nc (1)
program which will be used when sending files
'\" <</ital-is-var>>
.I to
'\" <<ital-is-var>>
the data server (authorized users only) through a SOCKS proxy server.
.TP
.BR \-n ", " \-\-no\-chat
Suppress the display of incoming chat messages including die rolls.
.TP
.BI "\-P\fR, \fP\-\-password " pass
For servers which require authentication, this specifies the password to gain entry to that server.
This is a fairly simple authentication mechanism intended to block nuisance connections, spam,
and accidental connections of legitimate clients to the wrong game server. If 
.I pass
is given as a single question mark
.RB (\*(lq ? \*(rq),
then the user will be prompted to enter their password manually when connecting to the server.
This avoids placing the plaintext password on the command line or in a configuration file.
.TP
.BI "\-p\fR, \fP\-\-port " port
If the
.B \-h
.RB ( \-\-host )
option is given, connect to the specified TCP
.I port
number on that host.  The default is port 2323.
.TP
.BI "\-\-preferences " path
Use the specified
.I path
instead of
.B ~/.gma/mapper/preferences.json
for the set of user preferences to use for this invocation. This allows
a completely separate set of preferences to be used for different users
or purposes. This command may not appear in a configuration file
(and is ignored if it is). It must be given only on the command line.
.TP
.BR \-l ", " \-\-preload
Pre-load all the cached images into memory at start-up, instead of loading them
as needed during the map's operation. Note that this only loads cached images
which are new enough that the mapper wouldn't check the server for newer versions
anyway, thus allowing a mapper client to be restarted mid-game with a minimum of
impact to game performance.
.TP
.BI "\-X\fR, \fP\-\-proxy\-host " host \fR[\fP: port \fR]\fP
For sending files
'\" <</ital-is-var>>
.I to
'\" <<ital-is-var>>
the server (for authorized users only), use the specified SOCKS5 proxy
server. (E.g.,
.BR "\-X proxy.example.org:1080" .)
.TP
.BI "\-x\fR, \fP\-\-proxy\-url " proxyurl
Use the given URL to connect through a proxy server to fetch image data.
This does not affect the connection to the map server used by GMA (yet).
(E.g., 
.BR "\-x http://proxy.example.org:1080" .)
.TP
.BI "\-\-scp\-dest " path
Specify the 
.I server-side
directory into which files will be uploaded (authorized users only).
This will be the top-level data directory for the mapper; subdirectory
names will be appended to this string.
.TP
.BI "\-\-scp\-path " path
Specify the path to the
.BR scp (1)
program which will be used to send files
'\" <</ital-is-var>>
.I to
'\" <<ital-is-var>>
the data server. (Authorized users only.)
.TP
.BI "\-\-scp\-server " hostname
The host name of the storage server. Only used when sending files
'\" <</ital-is-var>>
.I to
'\" <<ital-is-var>>
the server (authorized users only).
.TP
.BI "\-S\fR, \fP\-\-select " profile
Selects the named server
.I profile
from the
.B preferences.json
file without making it the selected profile
for other invocations of the mapper.
.TP
.BI "\-\-ssh\-path " path
Specify the path to the 
.BR ssh (1)
program used to send files
'\" <</ital-is-var>>
.I to
'\" <<ital-is-var>>
the storage server (authorized users only).
.TP
.BI "\-t\fR, \fP\-\-transcript " path
'\" <<TeX>>
'\" \label{mapper-transcript-opt}
'\" <</TeX>>
Records all chat window activity (including results of die rolls) to the
specified file
.IR path .
If this file exists, it will be appended to with the new information.
.RS
.LP
The following special tokens may appear in the
.I path
string, which will be replaced with values based on the time of day
the file is opened:
'\" <<desc>>
.TP 6
.B %a
Mon, Tue, etc.
.TP
.B %A
Monday, Tuesday, etc.
.TP
.B %b
Jan, Feb, etc.
.TP
.B %B
January, February, etc.
.TP
.B %d
Day of month (1\-31).
.TP
.B %j
Julian day of the year.
.TP
.B %m
Month (01\-12).
.TP
.B %y
Year (00\-99).
.TP
.B %Y
Year (all digits).
.TP
.B %H
Hour (00\-23).
.TP
.B %I
Hour (01\-12).
.TP
.B %M
Minutes (00\-59).
.TP
.B %S
Seconds (00\-59).
.TP
.B %p
AM or PM.
.TP
.B %D
Date (%m/%y/%d).
.TP
.B %r
Time (%I:%M:%S %p).
.TP
.B %R
Time (%H:%M).
.TP
.B %T
Time (%H:%M:%S).
.TP
.B %Z
Time zone name.
'\" <</>>
.RE
.TP
.BI "\-\-update\-url " url
Specifies the URL where updated versions of the 
.B mapper
program may be obtained. This enables automatic upgrades. The
.B mapper
will, with the user's approval, download updated versions of itself
from this URL and install them.
.TP
.BI "\-u\fR, \fP\-\-username " name
Sets the name used to identify you amongst the other players on your server.
If this option is not provided, your current system username will be used
instead.
'\" <</>>
.SH "INVOCATION"
.LP
As of this writing, the mapper still has not been ported to the new GMA
code in Python, and is still implemented as a Tcl/Tk script.  This means
you need to have a Tcl/Tk interpreter installed on your system. (See 
.B "http://tcl.tk"
if you need more information about that.) Since it's a GUI application,
it is run using the 
.B wish
command (the Tcl Windowing Shell).
.LP
We have noted that at least on the Mac platform, the
.B wish
program will refuse to let you expand the map window larger than
the largest dimensions of the screen(s) when it was launched,
so you want to plug in any projector or external displays before
starting the map.
.SH "INTERACTIVE USAGE"
.LP
The mapper shows the dungeon area around the players and includes features which
are helpful for managing game mechanics, particularly those relating to combat.
It is intended to be fairly self-explanatory (and I don't have time to thoroughly
document everything at the moment), so the following brief notes will hopefully suffice
to help a new user navigate its quirks.
.LP
The system menu bar is not used for this application, and is left to whatever the
.B wish
program sets it to for generic scripts. Instead, all of the interaction with the mapper
is done through its toolbar and context menu.
.SS "Tool Bar"
.LP
Across the top of the map is a graphical toolbar. Click on each button to activate its features. Note that some of these turn on/off different modes of operation for the map. When this happens, the mouse cursor will change to show the mode the map is currently in.
.LP
Each button is described briefly below.
The first block of buttons control the mapper's mode of operation.
They function as radio buttons (only one is active at a time,
and selecting one de-selects the previously selected one).
'\" <<list>>
.TP 10
Line Tool (cross-hair cursor)
Selects the line drawing tool. When this tool is active, click
the left button to start drawing a line, then click it again at
the other end of the line. You may continue clicking to get multiple
connected line segments (which all count as a single object on the
map). When finished, press the Escape key or click the middle button.  Cancel by pressing Escape or the middle button without having 
defined any points on the line at all.
Note that the current FILL color (not OUTLINE color) is used to
draw the line on the map.
.TP
Rectangle Tool (square cursor)
Selects the rectangle drawing tool. When this tool is active, click
the left button where you want one corner of the rectangle
to go, then click again where the diagonally opposite corner
should go.
The rectangle will be outlined in the OUTLINE color and filled
in with the FILL color.
Cancel by pressing Escape or the middle button.
.TP
Polygon Tool (polygon cursor)
This works like the Line Tool except that the region inside the
shape defined by the line segments is filled in with the FILL color,
while the outline is colored in the OUTLINE color.
.RS
.LP
Note that when this tool is selected, the two option buttons 
become active, offering some different options for how the lines
of the polygon are to be joined:
'\" <<list>>
.TP 8
Corner
Each time you click on this button, it cycles through the different
corner-join options: beveled, mitered, and round.
.TP
Spline
Each time you click on this button, it cycles through the spline 
levels from 0 (no splines, just straight lines), to 9 (use 9
lines between points to make a smooth curve).
.RE
'\" <</>>
.TP
Ellipse Tool (circle cursor)
This works like the Rectangle Tool except that it draws an elliptical shape inscribed within (tangent to) the rectangular area defined
by the two mouse clicks.
.TP
Arc Tool (diamond crosshair cursor)
This tool is for making various semicircular shapes. Its operation
is a little more complex than the others. When this tool is
active, the option is also active, allowing you to choose the
type of arc to create:
.RS
'\" <<desc>>
.TP 10
Arc type
Each time you click on this option button, it cycles through the
choices of arc types: pie slice, chord, and arc.
.LP
First, draw the elliptical shape for the arc (as if it were a
complete ellipse) as described for the Arc Tool. Then, move the
mouse horizontally to rotate the arc and vertically to adjust the
length of the arc. When satisfied, click the left button to complete
the arc.
Cancel by pressing Escape.
.RE
'\" <</>>
.TP
Text Tool (i-beam cursor)
This is used for placing text on the map. Its operation works much
like the stamp tool (q.v.), in that left-clicking on the canvas will
place a new copy of the current string at that location. If there is
no current string, you will be prompted to enter one.  Right-clicking
will prompt you for a new string rather than using the current one.
The current string is displayed below the tool bar.
.RS
.LP
With this tool active, a font selection button is available. Clicking
this toggles the font selection dialog. Changing the font in that dialog
will alter the font of the most recently placed text object (as long as
the text tool remains active) and sets the font for future text objects.
.LP
There is also an anchor selection button while this tool is active. This
shows as a centered cross (+) to indicate that the text will be centered
around the point where the mouse is clicked. Clicking on the anchor selection
button will cycle through all of the anchor directions available: north, south,
northeast, etc. These mean that the text will be aligned so that the point
where the mouse is clicked will be that direction from the text. Thus, for example,
selecting an anchor of \*(lqwest\*(rq (incidated by a left-pointing arrow) will
center the text vertically but align it horizontally so that the point
is to the left of the text.
.RE
.TP
Move Tool (iron cross cursor)
This is the default mode, and the one you should keep the mapper
in when not changing the map features. With this mode, you can
drag creatures around the map as described below.
.RS
.LP
If the mouse is not over a creature token when starting to
drag the mouse, the map grid itself is dragged, providing an easy way to scroll
the map.
.LP
If you hold down the shift key while clicking the left button on the canvas in
this mode, it will briefly show a marker to draw attention to the grid square
the mouse is in.
.RE
.TP
Delete (aka Cut) Tool (skull cursor)
With this tool active, any object you click on with the left button
will be deleted from the map immediately (no saving throw).
if you click where there are multiple overlapping objects,
you will be prompted to select which to delete. Press Escape if
you don't want to delete any of them.
.TP
Object Move Tool (multi-arrow cursor)
This tool allows the map objects (as opposed to creature tokens)
to be dragged to new locations. Note that you are dragging the object's
.I "reference point"
with the cursor. Once an object has been moved any distance with the
mouse, the arrow keys (or the standard 
.BR vi (1)
movement keys) may be used to \*(lqnudge\*(rq the object by one pixel
at a time up, down, left, or right; additionally the keys
.BR u ,
.BR d ,
.BR f ,
and
.BR b
may be used to move the object up, down, to the front, and to the back in the stacking order
'\" <</ital-is-var>>
.RI ( z
coordinate), respectively.
'\" <<ital-is-var>>
.TP
Stamp Tool (star cursor)
This allows graphical tiles to be \*(lqstamped\*(rq onto the map.
If there is a current tile already chosen, a new copy of it is placed
on the map with the upper-left corner at the point the mouse was clicked.
If no such tile was chosen, you will be prompted for its name. Right-clicking
will force the selection of a new tile image rather than re-stamping the
current one. See
.BR rendersizes (6)
for more information about the format of these tile files. They should be
rendered and (if using a map server) uploaded ahead of time so they are
visible in the map.
.LP
The next block of buttons control the appearance of
any new objects added to the map.
.TP
Fill Mode
Clicking on this button toggles whether the shape will be filled
or not. (Somewhat counter-intuitively, lines are filled with the
FILL color, not the OUTLINE color, so turning off fill will just
give you invisible lines.)
.TP
Fill Color
Clicking on this button selects the FILL color to be used to
fill in new object areas. This is disabled if fill mode is turned
off.
.TP
Outline Color
Clicking on this button selects the OUTLINE color to be used to
draw around new object areas.
.TP
Grid Snap
Clicking on this button cycles through the grid snap options:
.RS
'\" <<desc>>
.TP 
Off
Points may be added anywhere on the canvas (free form drawing).
.TP
1
Points may only be added at the intersections of grid lines.
.TP
1/2
Points may be added at grid intersections, and 1/2 way between them
horizontally or vertically.
.TP
1/3
Points may be added at grid intersections, and every 1/3 of the way
between them
horizontally or vertically.
.TP
1/4
Points may be added at grid intersections, and every 1/4 of the way
between them 
horizontally or vertically.
.RE
'\" <</>>
.TP
Line Width
Clicking on this button cycles through the line widths from thinnest to 
thickest.
'\" <</>>
.LP
The next block of buttons clear the map:
'\" <<desc>>
.TP
Clear Features
Clicking this button wipes the map clean except for creatures.
.TP
Clear Creatures
Clicking this button removes all creatures from the map.
.LP
The next block gives access to tactical displays.
.TP
Toggle Combat Mode
Normally, the GM console will automatically turn on combat mode,
but if you want to manually enable or disable it, click this button.
When active, the threat zones around each creature are highlighted
using colored cross-hatch patterns.
.RS
.LP
If health tracking is in effect (i.e., for creature objects which
have a non-empty 
.B HEALTH
attribute), a health bar is displayed across the bottom of each creature's token.
The appearance of this bar depends on the current health of the creature.  For
the description that follows, the significant health statistics are:
'\" <<desc>>
.TP
.I t
The total number of hit points the creature has when at maximum health.
.TP
.I x
The extra points (below zero) which define the amount of lethal damage
a dying creature can sustain before being dead. In Pathfinder and compatible
d20 games (and perhaps others), this is the Constitution score for the creature.
.TP
.I l
The number of hit points worth of 
.I lethal
damage sustained by the creature.
.TP
.I n
The number of hit points worth of
.I non-lethal
(i.e., subdual)
damage sustained by the creature.
'\" <</>>
.LP
The health bar indicates graphically the creature's health condition and relative
amount of damage they have taken, as follows:
'\" <<desc>>
.TP 13
Full health
A creature in full health will have a solid green bar across the entire width of their token's space
on the map.
.TP
Injured
The full width of the token space represents the creature's total (maximum) hit points 
.RI ( t ).
A red bar will start encroaching over the green in proportion to the number of lethal hit points
.RI ( l )
they have taken. A yellow bar will likewise represent the number of non-lethal hit points
.RI ( n )
taken. Thus, the health bar will be shifting more from green to red/yellow as the creature gets more
and more injured, until as it nears the point of meeting its maker, the entire bar will be red.
.TP
Flat-footed
A flat-footed creature (which does not also have any of the conditions listed below) will have a blue
frame around the health bar.
.TP
Staggered
When staggered due to non-lethal damage (i.e.,
.IR n >0
and
.IR l + n = t ),
the health bar has a yellow frame around it. The creature will move to unconscious if it suffers more
damage.
.TP
Unconscious
When unconscious due to non-lethal damage (i.e.,
.IR n >0
and
.IR l + n > t),
the health bar has a violet frame around it.
.TP
Disabled
When disabled, a red frame will appear around the health bar. 
The mapper will automatically assume disabled condition if a creature has exactly 0 hit points left (i.e.,
.IR l = t .)
.TP
Dying
When at negative hit points but still above the death level
.RI (\- x < t \- l < 0 ),
a red frame will appear but the red bar will retreat to the left as more lethal damage is taken,
until it's fully black at the point of death.
.TP
Stable
If dying but stabilized, the health bar will have a brown frame around it.
.TP
Dead
When completely mortally wounded
.RI ( t \- l <=\- x ),
the health bar is solid black.
.RE
'\" <</>>
.TP
Show HP Values
This toggles the display of health statistics for players (not monsters) over the
health bars. If only lethal damage has been inflicted, it displays
.RI \*(lq hp / max \*(rq
where
.I hp
is the current number of hit points remaining, out of a maximum of
.I max
hit points. If non-lethal damage has been suffered, then the display is
.RI \*(lq hp ( nl )\*(rq
where
.I nl
is the amount of non-lethal damage.
If a creature is fully dead, it simply says 
.RB \*(lq DEAD \*(rq.
.TP
Spell Area of Effect
This adds a spell area of effect to the battle grid. Once created,
this becomes a permanent map feature which may be removed using the
Cut Tool (q.v.).
When this tool is activated, two option buttons are enabled which allow
you to control the shape of the spell area:
.RS
'\" <<desc>>
.TP
Shape
This button cycles through the supported spell shapes: radius, cone, and ray.
.TP
Spread
This button toggles whether the spell effect \*(lqspreads\*(rq around corners.
This is not yet implemented.
.LP
Select the point of origin for the spell by clicking the left button over a
grid intersection (the tool will snap to intersections automatically). Then
move the mouse to the target point of the spell and click again to complete
the area. As you move the mouse, the spell's area and affected grids will be
shown.  The area of effect is filled in with cross-hatch patterns in the FILL
color.
Cancel by pressing Escape.
This is an active tool like the other drawing tools. When finished, select
another mode such as the Move Tool.
.RE
'\" <</>>
.TP
Ruler Tool
Selecting this tool allows you to measure the distance
along a path. Click the left button on a point, then
move the mouse to another point. If desired, multiple
points may be clicked to build a path. Middle-click or
press Escape to end the measurement.
.TP
Grid Display Toggle
Clicking this button turns on and off the display of the
gridlines on the map. This is a local display setting only,
and is not broadcast to other clients.
.TP
Die Roller
If connected to a server, this button brings up the chat window. In this window,
you may send and receive messages and die rolls to other connected users. 
This window is split into three adjustable panes, described individually below.
The division between each pane may be moved by dragging the mouse over the
separation point or pane handle.
.RS
'\" <<list>>
.TP
.B "Chat Messages Pane"
In the main portion of this pane displays incoming chat messages.
Each is prefixed with the name of the sender. If the message was
addressed only to you, the tag
.RI \*(lq (private) \*(rq
is added after the sender's name. If it was sent to a specific subset
of users, their names will be listed as
.RI \*(lq "(private to alice, bob, charlie)" \*(rq.
.RS
.LP
There are two entry lines below the chat window. The top one is for sending
chat messages. Anything typed in the entry box will be transmitted when the Return
key is hit. To the left of this entry box is a menu button which controls who
the message is sent to. If \*(lq(all)\*(rq is selected, the message is sent to all
listening clients (which need not be listed in the menu; the message will be sent to
everyone at the server level). If a recipient's name is selected, it will only be
sent to them. If another recipient's name is selected, they are
.I "added to"
the list of recipients. These selections are actually toggles\(emselecting a recipient's
name again will remove them from the list. This allows for messages to be sent to
any arbitrary subset of users. Selecting \*(lq(all)\*(rq will clear all selections again.
The \*(lqrefresh\*(rq button to the right of the entry box will update the recipient selection
menu with the current set of logged-in users.
.LP
The bottom entry line is for making die rolls. Into the entry box you may type any die roll
string such as would be accepted to the
.B DieRoller.do_roll()
method as documented in
.BR dice (3).
When the Return key is pressed, this die roll is sent to the server, which will roll the
dice and transmit the results just like a chat message (which includes the currently-selected
chat recipient list). The \*(lq(i)\*(rq button to the right of the entry box will bring up
a help window explaining what may be entered for die rolls.
'\" <<ital-is-var>>
.RE
.TP
.B "Recent Rolls Pane"
The most recent 10 rolls entered into the above-mentioned entry box are kept in a list in this
pane, with the most recent on top. Clicking on the die button next to any of these will re-roll
it again. If additional modifiers are in play, they can be typed into the entry box next to the 
die button. Whatever is entered is simply appended to the original die expression after a plus sign.
Thus, entering \*(lq5\*(rq will add \*(lq+5\*(rq to the roll, and entering \*(lq1d6 fire+3\*(rq
will add \*(lq+1d6 fire+3\*(rq to the roll.
.TP
.B "Preset Rolls Pane"
A set of commonly-needed die rolls may be pre-set into the tool and then invoked using the
third pane. Clicking the \*(lq(+)\*(rq button will add a new preset by prompting for its name,
description, and die roll. The name uniquely identifies the preset within the list. The description
will appear as a tooltip for your reference when looking at your presets. The new preset is
saved on the server and will be loaded into your client every time it's started. Presets are
invoked in the same manner as described above for recent rolls. Clicking the \*(lq(\-)\*(rq
button removes the preset from the list.
.RS
.LP
If a preset name includes a vertical bar (e.g.,
.RB \*(lq 12|WillSave \*(rq),
then only the part after the bar will be displayed on-screen, but the entire name is used to
sort the presets in the window. This allows arbitrary sort ordering without cluttering the display.
.LP
The file load and save buttons at the bottom of the pane are used to load and save the preset
list to local disk files which have the format documented in
.BR dice (5).
.RE
.RE
'\" <</>>
'\" <</>>
.LP
The final block of tool buttons control global operations of the mapper:
'\" <<desc>>
.TP
Zoom In
Double the visual size of grid blocks.
.TP
Zoom Out
Halve the visual size of grid blocks.
.TP
Un-Zoom
Restore the zoom level to normal.
.TP
Load
Add all the map objects from a disk file onto the map tool, replacing all the map features
previously on the map (but not the creatures).
.TP
Merge
Like Load, but add to the existing objects rather than replacing them.
.TP
Unload
All the objects saved to a selected disk file are 
.I erased
from the map.
.TP
Push
Push the entire contents of this map client to all other clients, replacing their
current contents. (Only available in store-and-forward mode, generally only for GM use.
Since the server now tracks game state and clients and re-sync with it directly,
there is no longer a need for clients to push their contents to each other, and that
was a problematic operation anyway.)
.TP
Store and Forward
Toggles store-and-forward mode. When enabled, this changes the behavior of the following
other buttons, providing a client update path that is much more efficient and less
error-prone than streaming the object updates through the server. Stand-alone
(non-networked) map clients should use the normal mode of operation instead.
.RS
.TP 7
Load
Prompts for the selection of a map file from disk as usual. However, rather than
loading that file directly, it checks to see that the file is available from the
server by checking the local cache and (if necessary) downloading from the server.
If the file is not found by those operations, it will be uploaded to the server
(assuming the user has the proper SSH access active at the time). Other clients
are then instructed to load the map file from the server. 
.TP
Merge
As with the Load button, but merges the map file with the existing map contents
rather than replacing them.
.TP
Unload
Ensures that a server copy of the map file exists as the Load button does, but then instructs
the remote clients to delete the contents of that file rather than sending individual
object deletion commands over the network to them.
.TP
Push
Saves the current map contents to a temporary file, uploads it to the server,
and then instructs the other clients to load that file.
.RE
.TP
Sync
'\" <</ital-is-var>>
.I "(Note that this button's function has changed as of version 3.25.)"
'\" <<ital-is-var>>
This clears the contents of the mapper client and requests a fresh set of data
from the server, thus synchronizing this client to be in line with the server's
idea of the current game state. Depending on how the server is configured, it
may automatically perform this operation for you when you connect to it.
.TP
Save
Save everything on the map to a disk file. You will be prompted to decide whether
this includes creatures as well.
.TP
Exit
Exit the mapper program.
'\" <</>>
.SS "Context Menu"
.LP
Clicking the right button over an object calls up a context-sensitive menu with the
following options. Not all options will be enabled in all cases.
Most of these involve performing actions on creatures. 
'\"This only works when the creature's
'\".I "reference grid"
'\"(the upper-left most grid in the space the creature occupies for creatures larger than
'\"medium-size) is right-clicked.
'\" <<list>>
.TP 20
.BI "Remove " name
Remove the creature from the map. 
If there are multiple creatures in the same grid, a submenu will allow you to select which one to remove, or allow you to remove them all.
.TP
.B "Add Player..."
Add one or more new player tokens into the grid clicked. This pops up a dialog box to enter the relevant
information about the new player:
.RS
'\" <<desc>>
.TP 8
.I name
The name by which the creature is to be known on the map. This
'\" <</ital-is-var>>
.I must
'\" <<ital-is-var>>
match the name the GM console is using to track initiative, or it'll never be highlighted
when its turn comes up (otherwise the name doesn't matter).  If the name coincides with 
graphical tile images already loaded, that image will be used instead of a plain circle with
the creature's name inside.  If a range in the form
.BI # n \- m
is appended to the name (usually with a space between the name and this notation),
then 
.IR m \- n +1
copies of the creature are added in a series of grid spaces starting with the one right-clicked
and continuing to the right.  For example, entering the name
\*(lqOrc #1\-3\*(rq will create three creatures, named
\*(lqOrc #1\*(rq,
\*(lqOrc #2\*(rq,
and
\*(lqOrc #3\*(rq.
Names must be unique. If another token was already on the map with the same name,
it is replaced with this one.
.RS
.LP
If a different image file is needed than the default (named the same as the person's name), 
specify it as 
.IB imagename = creaturename
(optionally followed by the 
.B #
notation described above).
.RE
.TP
.I size
The size, in units of grid squares (diameter), of the creature's token. 
You can also use standard size
designations
.B f
(fine),
.B d
(diminutive),
.B t
(tiny),
.B s
(small),
.B m
(medium),
.B l
(large),
.B h
(huge),
.B g
(gargantuan),
.B c
(colossal).
Where it makes a difference, indicate \*(lqtall\*(rq creatures by using
a capital letter and \*(lqwide\*(rq creatures with a lower-case one.
Since the recommended practice is to use the size codes, which means
you would use the same code for both
.I size
and 
.I area
fields, any time you type into the 
.I size
field, that will update 
.I area
at the same time. If a different
.I area
is needed, that can be edited afterward separately.
.TP
.I area
The threat area in the same units as the
.I size
field. This may also be
one of the standard size designator codes as with
.I size
(and this is generally preferred). In that case,
for size categories larger than medium, use upper-case
(tall) letters for size categories of tall creatures,
and lower-case for long creatures.
.TP
.I color
The color of the threat zone to draw around the creature
in combat mode.
.TP
.I reach?
Check this box if the creature has a reach weapon in hand.
'\" <</>>
.LP
Clicking
.B Ok
places the creature(s) on the grid and dismisses the dialog
box, while clicking
.B Apply
places the creature(s) but leaves the dialog up in case you want
to add more creatures to that grid square.
.RE
.TP
.B "Add Monster..."
Just like 
.B "Add Player" 
but adds a monster token.
.TP
.BI "Toggle Death for " name
Flips the creature token between living and dead states.
The mapper will automatically draw an \*(lqX\*(rq across the creature
token in addition to switching to the \*(lqdead\*(rq image (if images
are used).
.TP
.BI "Cycle Reach for " name
Cycles through the extra threat zone for reach weapons. This goes from normal threat
area to reach area and then to extended reach (both adjacent and reach zones together), then
back to normal again.
.TP
.BI "Toggle Spell Area for " name
Defines a spell effect which is described as a radius \*(lqcentered on you\*(rq (or some
creature). After choosing this item, click the left button to define where the radius extends
from the creature's perimeter.  If there was already a spell in effect, this cancels it.
This differs from the spell area tool from the toolbar in that it moves with the creature
and radiates from the creature's entire space rather than coming from a fixed point on the map.
The area is filled in with the current FILL color.
.TP
.BI "Polymorph " name
If alternative images are available for a creature, this selects which is to be displayed.
If the creature has a 
.B SKINSIZE
attribute which indicates the size of each of its polymorphed forms, then this menu will
allow you to choose between the number of forms defined for that creature, and will automatically
adjust the creature size at the same time. Otherwise, the mapper program doesn't know what
alternate forms are available so it will offer you a choice of three different forms, and will
make a best-effort attempt to locate and display the corresponding images. In this case,
you will need to manually adjust the size if needed.
.TP
.BI "Change Size of " name
Alter the size of a creature token.
.TP
.BI "Toggle Condition for " name
Selects a condition from the list of conditions built in to
.B mapper
or defined by the map service for custom game-specific conditions.
If the selected condition is already set for the target creature(s),
then it is removed. Otherwise it is added to the target(s).
.TP
.BI "Tag " name
Add a tag to a creature token to indicate their conditions. The recent tags which were set
are remembered and available in a sub-menu for convenience.
.TP
.BI "Set Elevation of " name
Specify how high above (or below) the obvious reference level a particular creature is.
This puts a tag in the upper right corner of their token in which is shown their elevation 
(as a simple number). The sub-menu triggered by this item allows easy selection of relative
distances, so you can quickly note that a creature moved up by 10 feet, for example.
Any arbitrary elevation may be directly input by selecting
.RB \*(lq (set) \*(rq
and typing the desired elevation into the dialog box that appears. If an absolute number is
input, that will be the new elevation. If the number begins with a 
.B +
or 
.B \-
sign, its value will be added or subtracted to the current elevation instead.
.TP
.B "Set Movement Mode"
Various modes of locomotion are denoted in the elevation tag (q.v.) by using
a different color for each. Use this menu item to select the mode currently
employed by the creature:
.RS
'\" <<desc>>
.TP
.B land
(white text on a black background)
.TP
.B fly
(black text on a deep sky blue background)
.TP
.B climb
(white text on a forest green background)
.TP
.B swim
(white text on a teal background)
.TP
.B burrow
(white text on a sienna background)
.RE
'\" <</>>
.TP
.B "Deselect All"
Cancels the multiple-creature selection.
.TP
.B "Show Visible Objects"
Moves the scrollbars to bring map features into view.
.TP
.B "Sync Others Views"
Moves all the other map clients scrollbars to see what this client is showing.
.TP
.B "Refresh Display"
Redraws the contents of the local mapper client. This does not reload any data (see the
.B Sync
button in the toolbar for that), but just locally re-draws everything again. This is useful,
for example, if the client didn't know about image data for tiles or creature tokens when it
first rendered the display. Often, it will work in the background to discover the missing
image data, so refreshing the display will then render everything properly.
.TP
.I name
Add a player token for the named player to the map, or move it to this location
if it was already on the map.
'\" <</>>
.SS "Creatures"
.LP
With the Move Tool (q.v.) selected, click and drag creatures to move them
around the map. 
'\"As with context menus, creatures larger than medium-size must
'\"be dragged from the upper-left corner of the rectangular space they fill on the board.
.LP
If you hold the control key down while left-clicking on creature tokens, it toggles whether
that creature is included in the group selection. When a group is selected, dragging any member
of the group moves the entire group at once. Context selections will also apply to the entire
group (e.g., to toggle death for all the selected tokens).
.LP
In combat mode, the area threatened by each creature is shown as a dashed outline,
and is cross-hatched when that player's turn is up for action. Arrows are drawn between
creatures in range to be melee targets.
.SH "WEIRD SIZES"
.LP
While the mapper implements the standard d20/Pathfinder creature size categories,
including tall (uppercase) and wide (lowercase) variants, sometimes there are special
cases which fall outside that list. The following special codes are also usable:
'\" <<desc>>
.TP 10
.B C80
Colossal creature with a size of 80 feet and an 80-foot threat zone. (Looking at you, Oliphaunt of Jandelay.)
.TP
.B M20/m20
Medium creature (5-foot space, 5-foot threat zone) with a 20-foot reach zone.
.TP
.B L0/l0
10-foot swarm (10-foot space, no threat or reach zone).
'\" <</>>
.SH INSTALLATION
.LP
To run the mapper, you'll need an up-to-date Tcl/Tk interpreter (8.6 or later), 
and the tcllib and tklib standard libraries.
.LP
Additionally you will need a copy of
.BR curl (1)
installed on your system. 
.LP
If you will be uploading content to the web server (and are authorized to do so),
you will also need to have
.BR ssh (1)
and 
.BR scp (1)
on your system.
.LP
You will need to ensure that the paths to these commands, server name(s), data paths, etc,
are configured correctly for your needs as well.
.SH "SEE ALSO"
.LP
.BR curl (1),
.BR scp (1),
.BR ssh (1),
.BR dice (3),
.BR dice (5),
.BR mapper (5),
.BR gma (6),
.BR mapper-protocol (7).
.SH AUTHORS
.LP
Steve Willoughby / steve@madscience.zone;
John Mechalas (elevation and movement modes).
.SH HISTORY
.LP
This document describes version 4.x of 
.BR mapper .
This introduces a breaking change from versions 3.x, mostly in terms of the communications
protocol used between the mapper server and clients and the way map data are represented
internally and in the disk files used by the mapper.
.LP
A version of 
.B mapper
was also in version 3 of GMA, but was different in operation.
.LP
As of version 3.25, the operation of the "Push to other clients" button was changed
so that it only works in store-and-forward mode (and is thus reserved essentially
for privileged users only). This was done because the old function of that button
is no longer needed and tended to cause more trouble than it was worth anyway.
.LP
Also changed in 3.25 is the function of the "Sync" button. It used to simply attempt to
reconnect a client to the server (which should automatically happen anyway). Now, since
the server tracks game state, simply exiting and restarting the map client accomplishes
the same effect (possibly better). Now this button requests a "sync" operation with the
server. 
.SH COMPATIBILITY
.LP
This program requires a reasonably modern version of Tcl/Tk, tcllib and tklib to function properly.
We strongly recommend running it with the latest versions of all of those.
.LP
It is known to run on the macOS Mojave platform (tested on 10.14.6), 
macOS Catalina (tested on 10.15.3, but note that Apple's support for python3, tcl, and tk is such that
you may want to install your own versions of those tools); and should run fine on any
modern *NIX-like platform (tested on FreeBSD 12.0, Ubuntu 18.04 LTS, and Ubuntu 16.04 LTS).
.LP
It was also tested (briefly) on Windows 10.
See the detailed installation and usage tutorials in the
'\" <</ital-is-var>>
.IR "GMA Game Master's Guide" .
'\" <<ital-is-var>>
.SH FILES
'\" <<list>>
.TP
.B ~/.gma/mapper/preferences.json
Preferences data storage file, normally edited via the in-application
preferences editor window.
.TP
.B ~/.gma/mapper/mapper.conf
Default configuration file read if no explicit
.B \-C
or
.B \-\-config
option is given and no 
.B preferences.json
file was read.
.TP
.B ~/.gma/mapper/style.conf
Default custom style configuration file read if no explicit
.B \-s
or
.B \-\-style
option is given.
.TP
.B ~/.gma/mapper/debug.log
Location where debugging messages are written in addition to being displayed in the debugging window.
.TP
.B ~/.gma/mapper/logs
Runtime logfiles are stored here for each execution of the mapper.
.TP
.B ~/.gma/mapper/cache
Cached copies of images and other content are stored here to improve speed of the mapper.
'\" <</>>
.SH BUGS
.LP
There are numerous hacks in the program which really should not be there.
In fact, at this point the thing just needs to be rewritten using the newer
GMA code base.
.LP
Calculation of threatened spaces needs to take elevation into account.
(Although the mapper now includes a 3D-aware distance calculation when requested.)
.LP
The
.B \-h
option really should have been for
.B \-\-help
to conform to usual command-line conventions, and the 
.B \-\-host
option should instead have been
.BR \-H .
This may change in the future.
.LP
In previous versions,
.B \-\-keep\-tools
.RB ( \-k )
was called 
.B \-\-master
.RB ( \-m ),
but this never really made sense, as it didn't really mean the mapper
was in any sort of controlling or leadership role. It only meant it would
refuse to turn off its own toolbar if asked to do so. The new name is
more descriptive of the actual function.
.LP
Some of the menu behavior required by the mapper client has been shown not to
work with Tcl/Tk version 8.6, so the mapper avoids using those features when
the Tcl/Tk version is less than 8.7.
.SH "DEPRECATED FEATURES"
.LP
The preferred way to configure
.B mapper
is to use the built-in preferences editor. This obsoletes the use of the older
simple configuration file which needed to be edited by hand, and makes it unnecessary
to use CLI options to specify the runtime parameters for the mapper's operation.
The use of the legacy configuration file is still supported, however, as is the
use of CLI options where desired for 
'\" <</ital-is-var>>
.I ad-hoc
changes from the saved preferences.
.LP
However, the switch to the preferences system makes the following CLI options now
obsolete and they no longer perform any function:
.BR \-\-generate\-config ,
.BR \-\-generate\-style\-config ,
.BR \-s ,
and
.BR \-\-style .
.SH COPYRIGHT
Part of the GMA software suite, copyright \(co 1992\-2023 by Steven L. Willoughby, Aloha, Oregon, USA. All Rights Reserved. Distributed under BSD-3-Clause License. \"@m(c)@