'\" t
'\" <<ital-is-var>>
'\" <<bold-is-fixed>>
.TH MAPPER 5 "GMA-Mapper 4.15.2" 21-Sep-2023 "File Formats" \" @@mp@@
.SH NAME
mapper \- battle grid save file format
.SH DESCRIPTION
.LP
The version 22 file format for the
.BR mapper (6)
battle grid program is described in this document.
.LP
The file is UTF-8-encoded Unicode, of which 7-bit ASCII is a subset.
.LP
The first line MUST have the form
.RS
.LP
.BI __MAPPER__: version
.RE
.LP
where
.I version
is the map file format version this file conforms to.
Following this are a number of data records of the form
.RS
.LP
.I type
.I object
.RE
.LP
The
.I object
is a JSON-formatted data structure appropriate for the
.I type
of value being described by this record.
The line MUST begin with the 
.I type
designation. 
The JSON-formatted
.I object
data must either be completely contained on one line, or be continued
over multiple following lines, all of which SHOULD be indented by at least
one space or tab. A line MUST NOT begin with the character \[Fo] unless it is the start of a new
record or the EOF marker (i.e., this character in the first position on a line marks the start of
a new record).
.LP
The delimiter characters \[Fo] and \[Fc] are Unicode codepoints U+AB and U+BB respectively.
.LP
JSON field names are case-sensitive. Their values are strings unless otherwise
noted.
.LP
The final line of the file MUST be the text
.B \[Fo]__EOF__\[Fc]
to indicate the end of the data.
.LP
The following data records MAY be present:
'\" <<list>>
.TP
.B \[Fo]__META__\[Fc]
File metadata. The JSON object may contain the following fields:
.RS
'\" <<list>>
.TP
.BI Timestamp " (int)"
Modificaion time as a number of seconds from the epoch.
.TP
.B DateTime
The modification time as a human-readable string value in any form.
(Software always uses the
.I Timestamp
field; this is only for the convenience of human readers.)
.TP
.B Comment
Random comments about the file.
.TP
.B Location
The name or description of the location described by the file.
.TP
.BI FileVersion " (int)"
When a file is read, this field is populated with the input file's format version number.
It is ignored if present when writing a map file.
.RE
'\" <</>>
.TP
.BI \[Fo] element_type \[Fc]
Defines a map element using a JSON structure identical to the JSON
data defined in the mapper protocol in
.BR mapper (6)
for the
.BI LS- element_type
command.
This includes
.IR element_type s
.BR ARC ,
.BR CIRC ,
.BR LINE ,
.BR POLY ,
.BR RECT ,
.BR SAOE ,
.BR TEXT ,
and
.BR TILE .
.TP
.B \[Fo]IMG\[Fc]
Declares the server ID by which a named image may be retrieved by the client
(or a local pathname if the file is local)
using a JSON data structure similar to that of the
.B AI
server command.
See the example below.
.TP
.B \[Fo]MAP\[Fc]
Declares the existence of a map file which may be retrieved from the server
using a JSON data structure identical to that of the
.B L
server command, except that only the 
.I File
field is used.
.TP
.B \[Fo]CREATURE\[Fc]
Places a creature token on the map using a JSON structure identical to that used
by the
.B PS
server command.
'\" <</>>
.SH COMPATIBILITY
.LP
Programs are expected to silently ignore data fields which they don't expect,
and to default any missing fields with the zero value for their data type.
Thus, it is not always necessary for the file version number to increase
if a change in data fields would produce a benign default behavior given
these assumptions.
.SH EXAMPLE
'\" <<TeX>>
'\" \begin{Coding}
'\" |__MAPPER__:22|\\
'\" \guillemotleft|__META__|\guillemotright{}| {|\\
'\" |  "Timestamp": 1650611775,|\\
'\" |  "DateTime": "Fri Apr 22 00:16:15 PDT 2022",|\\
'\" |  "Location": "Room 12 of the Dungeon"|\\
'\" |}|\\
'\" \guillemotleft|LINE|\guillemotright{}| {|\\
'\" |  "ID": 1,|\\
'\" |  "Fill": "#00e400",|\\
'\" |  "X": 425,|\\
'\" |  "Y": 107,|\\
'\" |  "Z": 1,|\\
'\" |  "Points": [|\\
'\" |    {"X": 433, "Y": 337}, |\\
'\" |    {"X": 553, "Y": 392}, |\\
'\" |    {"X": 600, "Y": 243},|\\
'\" |    {"X": 424, "Y": 108}|\\
'\" |  ],|\\
'\" |  "Width": 5|\\
'\" |}|\\
'\" \guillemotleft|RECT|\guillemotright{}| {|\\
'\" |  "ID": 2,|\\
'\" |  "Line": "black",|\\
'\" |  "Fill": "#00e400",|\\
'\" |  "Width": 5,|\\
'\" |  "X": 593,|\\
'\" |  "Y": 122,|\\
'\" |  "Z": 2,|\\
'\" |  "Points": [|\\
'\" |    {"X": 807, "Y": 443}|\\
'\" |  ]|\\
'\" |}|\\
'\" \guillemotleft|IMG|\guillemotright{}| {|\\
'\" |  "Name": "re5_e2",|\\
'\" |  "Sizes": [|\\
'\" |    {"File": "SJy9rpbTDElsCfklYHMvsgre5_e2@50", "Zoom": 1.0},|\\
'\" |    {"File": "SJy9rpbTDElsCfklYHMvsgre5_e2@100", "Zoom": 2.0}|\\
'\" |  ]|\\
'\" |}|\\
'\" \guillemotleft|__EOF__|\guillemotright{}
'\" \end{Coding}
.LP
.nf
.na
\fB
__MAPPER__:22
\[Fo]__META__\[Fc] {
  "Timestamp": 1650611775,
  "DateTime": "Fri Apr 22 00:16:15 PDT 2022",
  "Location": "Room 12 of the Dungeon"
}
\[Fo]LINE\[Fc] {
  "ID": 1,
  "Fill": "#00e400",
  "X": 425,
  "Y": 107,
  "Z": 1,
  "Points": [
    {"X": 433, "Y": 337}, 
    {"X": 553, "Y": 392}, 
    {"X": 600, "Y": 243},
    {"X": 424, "Y": 108}
  ],
  "Width": 5
}
\[Fo]RECT\[Fc] {
  "ID": 2,
  "Line": "black",
  "Fill": "#00e400",
  "Width": 5,
  "X": 593,
  "Y": 122,
  "Z": 2,
  "Points": [
    {"X": 807, "Y": 443}
  ]
}
\[Fo]IMG\[Fc] {
  "Name": "re5_e2",
  "Sizes": [
    {"File": "SJy9rpbTDElsCfklYHMvsgre5_e2@50", "Zoom": 1.0},
    {"File": "SJy9rpbTDElsCfklYHMvsgre5_e2@100", "Zoom": 2.0}
  ]
}
\[Fo]__EOF__\[Fc]
\fP
.fi
.ad
'\" <</TeX>>
.LP
This file contains two objects: 
.LP
#1 is a line in the shade of green with (R=0, G=0xe4, B=0), with 
line segments of width 5 going between points (425,107) \- 
(433,337) \- (553,392) \- (600,243) \- (424,108).
.LP
#2 is a black rectangle filled in with the same shade of 
green as line #1, with a line width of 5, between opposing 
corners (593,122) and (807,443).
.LP
Additionally, it indicates that an image called \*(lqre5_e2\*(rq
may be found with server ID \*(lqSJy9rpbTDElsCfklYHMvsgre5_e2@50\*(rq
at zoom factor 1.0, or with server ID \*(lqSJy9rpbTDElsCfklYHMvsgre5_e2@100\*(rq
at zoom factor 2.0.
.SH "SEE ALSO"
.LP
.BR mapper (6),
.BR rendersizes (6).
.SH FILES
The exact location of cache files may vary depending on the
operating system platform. For example, on macOS the
.B cache
directory is found in 
.BR ~/Library/Caches/gma-mapper .
On Linux and FreeBSD it is located in
.BR ~/.caches/gma-mapper .
On Windows it is located in
.BR %LOCALAPPDATA%\egma-mapper .
If no specific cache directory can be determined,
.B ~/.gma/mapper/cache
is used by default.
'\" <<desc>>
.TP
.BI ~/.gma/mapper/cache/ name @ zoom .gif
The GIF-format file for image with the given
.I name
and scaled to the given
.I zoom
factor.
.TP
.BI ~/.gma/mapper/cache/ id .map
The map file with server ID
.IR id .
'\" <</>>
.SH HISTORY
.LP
This describes the 4.x versions of
.BR mapper .
.SS "Changes as of File Format 2"
.LP
Version 2 files differ from version 1 files in that they add the
.BR JOIN ,
.BR SPLINE ,
.BR START ,
.B EXTENT
and
.B ARCMODE
attributes, the
.B arc
object type, and the "no-fill" (empty string) mode for the
.B FILL
attribute.
.SS "Changes as of File Format 3"
.LP
This file retains compatibility with the version 2 format,
with the following differences.
.LP
Each object now has a
.I z
coordinate in addition to the 
.RI ( x , y )
coordinates of its reference point as in previous versions.
The
.I z
coordinate indicates the display \*(lqstacking order\*(rq 
of objects on the screen.  Each object is \*(lqflat\*(rq
and are rendered in order from the smallest to the largest
value of
.I z
so that the lowest
.I z
value is at the \*(lqbottom\*(rq with the others overlapping
on top of them.  These serve only to indicate the relative
positioning of objects.  There is no absolute meaning to
any particular value for
.IR z .
.LP
Added the
.BR HIDDEN ,
.BR LEVEL ,
and 
.B GROUP
object attributes.
.SS "Changes as of File Format 4"
.LP
This format is compatible with File Format 3, except that it adds the following 
attributes to support tile objects:
'\" <<desc>>
.TP
.B LAYER
The layer attribute may now include the value
.B tiles
which is rendered below everything else, including the grid lines.
.TP
.B IMAGE
This attribute appeared for the first time in this version.
.TP
.B SIZE
This attribute appeared for the first time in this version.
'\" <</>>
.LP
Programs which read newer version files should deal 
correctly with older files which do not contain the newer
elements.
.SS "Changes as of File Format 5"
.LP
This introduced images, creatures, and spell areas of effect.
.SS "Changes as of File Format 6"
.LP
The image definition syntax was extended to allow externally downloaded
image files.
.SS "Changes as of File Format 7"
.LP
Additional creature attributes were added, such as
.BR NOTE 
and
.BR SKIN .
.SS "Changes as of File Format 8"
.LP
Added text objects. This includes the addition of the
.BR ANCHOR ,
.BR FONT ,
and
.B TEXT
attributes.
.SS "Changes as of File Format 9"
.LP
Added 
.B ARROW
and 
.B DASH
attributes. For backward compatibility with format 8,
if either of these are missing from the file, defaults
are assumed.
.SS "Changes as of File Format 10"
.LP
Added
.B ELEV
and
.B MOVEMODE
attributes.
.SS "Changes as of File Format 11"
.LP
Added
.B HEALTH
attribute.
.SS "Changes as of File Format 12"
.LP
Added 
.B F
record type.
.SS "Changes as of File Format 13"
.LP
Added the optional
.I blur
element of the
.B HEALTH
attribute.
Removed the
.B SELECTED
attribute. This is a transient state used during the mapper program's
operation and has no point being saved with the object. This attribute
was moved to the private name
.B _SELECTED
instead.
.SS "Changes as of File Format 14"
.LP
Added the
.B STATUSLIST
attribute.
.SS "Changes as of File Format 15"
.LP
Added the
.B SKINSIZE
attribute.
.SS "Changes as of File Format 16"
.LP
Added the
.B LOCKED
attribute.
.SS "Changes as of File Format 17"
.LP
.B SIZE
only applies to creature tokens.
The version 16 document incorrectly specified that map elements
(notably tiles) also had a
.B SIZE
attribute but this was never implemented. Instead, they had
unofficial attributes
.B _BBHEIGHT
and
.B _BBWIDTH
which have now been promoted to official status as
.B BBHEIGHT
and
.BR BBWIDTH .
.SS "File Formats 18 and 19"
.LP
These are reserved for use in case map format changes are needed before
moving to map version 4.x.
.SS "Changes as of File Format 20"
.LP
This version introduced the JSON-based file format, replacing the older
key/value line sequence.
.SS "Changes as of File Format 21"
.LP
The fields for creatures have been changed as documented in
.BR mapper-protocol (7).
.SS "Changes as of File Format 22"
.LP
Animation support introduced in protocol 407 alters the format
of the
.B IMG
records in this file correspondingly.
.SH AUTHORS
.LP
Steve Willoughby / steve@madscience.zone;
Elevation and movement modes added by John Mechalas.
.SH BUGS
.LP
The
.BR LEVEL ,
.BR GROUP ,
and
.B LAYER
attributes are not actually implemented yet in the mapper program. They're documented
here and will be accepted by the mapper but none of their behavior documented above
will actually happen.
.LP
The
.B token
object type is deprecated and clients are free to be unaware of its existence.
.LP
The current implementation of file reading code in GMA will accept input more
permissively than this spec requires, strictly speaking (e.g., an otherwise valid JSON
object where the final brace is not by itself on a line), but this behavior should not
be construed as a requirement for other code. File readers and writers should follow 
this specification as the authoritative standard.
.SH COPYRGHT
Part of the GMA software suite, copyright \(co 1992\-2023 by Steven L. Willoughby, Aloha, Oregon, USA. All Rights Reserved. Distributed under BSD-3-Clause License. \"@m(c)@