'\" t
'\" <<bold-is-fixed>>
'\" <<ital-is-var>>
.TH GMACOLORS 3 "GMA-Mapper 4.6.1" 20-May-2023 "API Functions" \" @@mp@@
.SH NAME
gmacolors \- Color support utilities
.SH SYNOPSIS
'\" <<usage>>
.na
(If package installed globally)
.br
.B package
.B require
.B gmacolors
.LP
(Otherwise)
.br
.B source
.B gmacolors.tcl
.LP
.B ::gmacolors::rgb_name
.I color
\[->]
.I name
.ad
'\" <</usage>>
.SH DESCRIPTION
.LP
This module provides a set of miscellaneous utility functions dealing with colors.
'\" <<list>>
.TP 10
.BI "::gmacolors::rgb_name " color
Given a
.I color
code in the format
.BI # rrggbb
this function returns the X11 color code name corresponding to that RGB color value.
If none is found, the original
.I color
string is returned.
'\" <</>>
.SH AUTHOR
.LP
Steve Willoughby / steve@madscience.zone.
.SH COPYRGHT
Part of the GMA software suite, copyright \(co 1992\-2023 by Steven L. Willoughby, Aloha, Oregon, USA. All Rights Reserved. Distributed under BSD-3-Clause License. \"@m(c)@